package yuma140902.mcmods.yumalib.recipe;

public class RecipeStat {
	public static final float
		SMELTING_XP_FOR_STONE = 0.1F,
		SMELTING_XP_FOR_LOG = 0.15F,
		SMELTING_XP_FOR_CACTUS = 0.2F,
		SMELTING_XP_FOR_CLAY = 0.3F,
		SMELTING_XP_FOR_FOOD = 0.35F,
		SMELTING_XP_FOR_ORE = 0.7F,
		SMELTING_XP_FOR_RARE_ORE = 1.0F;
	
	public static final String
		OREDIC_LOG = "logWood",
		OREDIC_PLANK = "plankWood",
		OREDIC_WOODEN_SLAB = "slabWood",
		OREDIC_WOODEM_STAIR = "stairWood",
		OREDIC_STICK = "stickWood",
		OREDIC_SAPLING = "treeSapling",
		OREDIC_LEAVES = "treeLeaves",
		OREDIC_VINE = "vine",
		
		OREDIC_ORE_GOLD = "oreGold",
		OREDIC_ORE_IRON = "oreIron",
		OREDIC_ORE_LAPIS = "oreLapis",
		OREDIC_ORE_DIAMOND = "oreDiamond",
		OREDIC_ORE_REDSTONE = "oreRedstone",
		OREDIC_ORE_EMERALD = "oreEmerald",
		OREDIC_ORE_QUARTZ = "oreQuartz",
		OREDIC_ORE_COAL = "oreCoal",
		
		OREDIC_BLOCK_GOLD = "blockGold",
		OREDIC_BLOCK_IRON = "blockIron",
		OREDIC_BLOCK_LAPIS = "blockLapis",
		OREDIC_BLOCK_DIAMOND = "blockDiamond",
		OREDIC_BLOCK_REDSTONE = "blockRedstone",
		OREDIC_BLOCK_EMERALD = "blockEmerald",
		OREDIC_BLOCK_QUARTZ = "blockQuartz",
		OREDIC_BLOCK_COAL = "blockCoal",
		
		OREDIC_INGOT_IRON = "ingotIron",
		OREDIC_INGOT_GOLD = "ingotGold",
		OREDIC_NUGGET_IRON = "nuggetIron",
		OREDIC_NUGGET_GOLD = "ingotGold",
		
		OREDIC_GEM_DIAMOND = "gemDiamond",
		OREDIC_GEM_EMERALD = "gemEmerald",
		OREDIC_GEM_LAPIS = "gemLapis",
		OREDIC_GEM_QUARTZ = "gemQuartz",
		OREDIC_DUST_REDSTONE = "dustRedstone",
		OREDIC_DUST_GLOWSTONE = "dustGlowstone",
		
		OREDIC_BRICK = "ingotBrick",
		OREDIC_NETHER_BRICK = "ingotBrickNether",
		OREDIC_PRISMARINE = "gemPrismarine",
		OREDIC_PRISMARINE_DUST = "dustPrismarine",
		
		OREDIC_CROP_WHEAT = "cropWheat",
		OREDIC_CROP_POTATO = "cropPotate",
		OREDIC_CROP_CARROT = "cropCarrot",
		OREDIC_CROP_NETHERWART = "cropNetherWart",
		OREDIC_CROP_SUGERCANE = "sugercane",
		OREDIC_CROP_CACTUS = "blockCactus",
		
		OREDIC_DYE = "dye",
		OREDIC_PAPER = "paper",
		
		OREDIC_SLIMEBALL = "slimeball",
		OREDIC_ENDERPEARL = "enderpearl",
		OREDIC_BONE = "bone",
		OREDIC_GUNPOWDER = "gunpowder",
		OREDIC_STRING = "string",
		OREDIC_NETHERSTAR = "netherStar",
		OREDIC_LEATHER = "leather",
		OREDIC_FEATHER = "feather",
		OREDIC_EGG = "egg",
		OREDIC_RECORD = "record",
		
		OREDIC_DIRT = "dirt",
		OREDIC_GRASS = "grass",
		OREDIC_STONE = "stone",
		OREDIC_COBBLESTONE = "cobblestone",
		OREDIC_GRAVEL = "gravel",
		OREDIC_SAND = "sand",
		OREDIC_SANDSTONE = "sandstone",
		OREDIC_NETHERRACK = "netherrack",
		OREDIC_OBSIDIAN = "obsidian",
		OREDIC_GLOWSTONE = "glowstone",
		OREDIC_ENDSTONE = "endstone",
		OREDIC_TORCH = "torch",
		OREDIC_WORKBENCH = "workbench",
		OREDIC_SLIME_BLOCK = "blockSlime",
		OREDIC_PRISMARINE_BLOCK = "blockPrismarine",
		OREDIC_PRISMARINE_BRICK = "blockPrismarineBrick",
		OREDIC_DARK_PRISMARINE_BLOCK = "blockPrismarineDark",
		OREDIC_GRANITE = "stoneGranite",
		OREDIC_POLISHED_GRANITE = "stoneGranitePolished",
		OREDIC_DIORITE = "stoneDiorite",
		OREDIC_POLISHED_DIORITE = "stoneDioritePolished",
		OREDIC_ANDESITE = "stoneAndesite",
		OREDIC_POLISHED_ANDESITE = "stoneAndesitePolished",
		OREDIC_GLASS_COLORLESS = "blockGlassColorless",
		OREDIC_GLASS = "blockGlass",
		OREDIC_PANE_GLASS_COLORLESS = "paneGlassColorless",
		OREDIC_PANE_GLASS = "paneGlass",
		
		OREDIC_CHEST = "chest",
		OREDIC_WOODEN_CHEST = "chestWood",
		OREDIC_ENDER_CHEST = "chestEnder",
		OREDIC_TRAPPED_CHEST = "chestTrapped";


}
